# Generated by Django 4.2.20 on 2025-04-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='gpa',
            new_name='high_school_gpa',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='dormitory_requested',
            new_name='is_dormitory_requested',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='scholarship_requested',
            new_name='is_scholarship_requested',
        ),
        migrations.RemoveField(
            model_name='application',
            name='english_proficiency',
        ),
        migrations.AddField(
            model_name='application',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='english_proficiency_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='english_proficiency_type',
            field=models.CharField(blank=True, choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('duolingo', 'Duolingo'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='extracurricular_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='personal_statement',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
