# Generated by Django 4.2.20 on 2025-04-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
        ('applications', '0002_rename_gpa_application_high_school_gpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_programs', to='universities.university'),
        ),
    ]
