# Generated by Django 4.2.20 on 2025-04-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_delete_program'),
        ('applications', '0003_alter_program_university'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university'),
        ),
    ]
