# Generated by Django 4.2.20 on 2025-04-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('website', models.URLField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('established_year', models.IntegerField()),
                ('accreditation_info', models.TextField()),
                ('ranking', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'university',
                'verbose_name_plural': 'universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=20)),
                ('description', models.TextField()),
                ('duration_years', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tuition_fee_per_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('language_of_instruction', models.CharField(choices=[('kazakh', 'Kazakh'), ('russian', 'Russian'), ('english', 'English')], max_length=20)),
                ('credits_required', models.IntegerField()),
                ('admission_requirements', models.TextField()),
                ('application_deadline', models.DateField()),
                ('start_date', models.DateField()),
                ('scholarships_available', models.BooleanField(default=False)),
                ('has_dormitory', models.BooleanField(default=False)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'ordering': ['university', 'name'],
            },
        ),
    ]
