# Generated by Django 4.2.20 on 2025-04-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
