# Generated by Django 4.2.20 on 2025-04-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_delete_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='students_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('international', 'International')], default='public', max_length=20),
        ),
    ]
