# Generated by Django 4.2.20 on 2025-04-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_country_university_students_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private'), ('international', 'International')], default='public', max_length=20, null=True),
        ),
    ]
