# Generated by Django 4.2.20 on 2025-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_alter_university_country_alter_university_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='university_documents/'),
        ),
    ]
